# Generated by Django 4.2.4 on 2023-08-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_instructor_firstshift_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='roll',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='cr',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
