# Generated by Django 4.2.4 on 2023-08-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_student_roll_alter_student_cr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='cr',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
