# Generated by Django 4.2.4 on 2023-08-17 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_student_cr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Went',
            new_name='went',
        ),
    ]
