# Generated by Django 4.2.4 on 2023-08-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_student_cr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='firstShift',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='secondShift',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='firstShift',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='secondShift',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
