# Generated by Django 4.2.4 on 2023-08-19 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_instructor_firstshift_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instrument',
            old_name='InstrumentImage',
            new_name='instrumentImage',
        ),
    ]
