# Generated by Django 4.2.4 on 2023-10-23 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_instrumentimage_instrument_instrumentimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('heading', models.CharField(blank=True, max_length=300, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('noticeImage', models.ImageField(blank=True, null=True, upload_to='noticeImage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
